- name: Preparar Display.Driver
      shell: powershell
      run: |
        $path = Get-ChildItem -Recurse -Directory -Filter "Display.Driver" | Select-Object -First 1

        if (-not $path) {
          Write-Error "Display.Driver NÃO encontrada!"
          exit 1
        }

        # remover se já existir
        if (Test-Path "Display.Driver") {
          Remove-Item -Recurse -Force Display.Driver
        }

        Move-Item $path.FullName Display.Driver
