name: Build Windows LTSC ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =============================
      # DOWNLOAD ISO (PARTES)
      # =============================
      - name: Download ISO parts
        run: |
          mkdir ISO
          cd ISO
          curl -L -o Win10.7z.001 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.001
          curl -L -o Win10.7z.002 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.002
          curl -L -o Win10.7z.003 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.003

      # =============================
      # EXTRAIR ISO
      # =============================
      - name: Extract ISO
        run: |
          cd ISO
          7z x Win10.7z.001

      # =============================
      # DOWNLOAD PROJETO NTLITE
      # =============================
      - name: Download ProjetoNTLite
        run: |
          curl -L -o ProjetoNTLite.zip https://github.com/Loopz976/ltsc-auto-builder/releases/download/projetontlite/ProjetoNTlite.zip

      - name: Extract ProjetoNTLite
        run: |
          7z x ProjetoNTLite.zip -oProjeto

      # =============================
      # RODAR NTLITE
      # =============================
      - name: Run NTLite
        run: |
          Projeto\NTLite\NTLite.exe ^
          /image:"ISO" ^
          /preset:"Preset\W10_19044_FINAL_NVIDIA_21_04_26.xml" ^
          /apply ^
          /save ^
          /exit

      # =============================
      # CRIAR ISO FINAL
      # =============================
      - name: Create ISO
        run: |
          oscdimg -bISO\boot\etfsboot.com -u2 -h -m -o ISO C:\output.iso

      # =============================
      # COMPACTAR EM PARTES 1900MB
      # =============================
      - name: Split ISO
        run: |
          7z a -v1900m Win10LTSC_21.04.2026_NTLite_actions.7z C:\output.iso

      # =============================
      # UPLOAD PARA RELEASE
      # =============================
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-ltsc
          name: Win10 LTSC 21.04.2026 NTLite actions
          files: Win10LTSC_21.04.2026_NTLite_actions.7z*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
