name: Build Windows ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install 7zip
      run: choco install 7zip -y

    # =========================
    # BAIXAR ISO (3 PARTES)
    # =========================
    - name: Download ISO Parts
      run: |
        mkdir ISO
        cd ISO
        curl -L -o part1.7z.001 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.001
        curl -L -o part1.7z.002 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.002
        curl -L -o part1.7z.003 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc21h2-base-2/Win10LTSC21H2Base.7z.003

    # =========================
    # EXTRAIR ISO
    # =========================
    - name: Extract ISO
      shell: cmd
      run: |
        cd ISO
        7z x part1.7z.001 -oISO_EXTRACTED -y

    # =========================
    # BAIXAR PROJETO NTLITE
    # =========================
    - name: Download ProjetoNTLite
      run: |
        curl -L -o ProjetoNTLite.zip https://github.com/Loopz976/ltsc-auto-builder/releases/download/projetontlite/ProjetoNTlite.zip

    - name: Extract ProjetoNTLite
      run: |
        7z x ProjetoNTLite.zip -oProjetoNTLite -y

    # =========================
    # RODAR NTLITE (CORRIGIDO)
    # =========================
    - name: Run NTLite (Silent + Log)
      shell: powershell
      run: |
        $log = "ntlite.log"

        Start-Process "ProjetoNTLite\NTLite\NTLite.exe" `
          -ArgumentList "/silent /load:Preset\W10_19044_FINAL_NVIDIA_21_04_26.xml /apply /exit /log:$log" `
          -Wait

        echo "==== LOG NTLITE ===="
        Get-Content $log -Tail 200

    # =========================
    # CRIAR ISO
    # =========================
    - name: Create ISO
      run: |
        mkdir FINAL
        oscdimg -bISO\ISO_EXTRACTED\boot\etfsboot.com -u2 -h -m -o -lWIN10_CUSTOM ISO\ISO_EXTRACTED FINAL\Win10LTSC_21.04.2026_ntlite_actions.iso

    # =========================
    # SPLIT ISO 1900MB
    # =========================
    - name: Split ISO
      run: |
        7z a -v1900m FINAL\Win10LTSC_21.04.2026_ntlite_actions.7z FINAL\Win10LTSC_21.04.2026_ntlite_actions.iso

    # =========================
    # UPLOAD RELEASE
    # =========================
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: Win10LTSC 21.04.2026 ntlite actions
        files: FINAL\*.7z*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
