name: Teste Windows 11 AUTO

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: windows-latest

    steps:
    - name: Baixar UUP Dump Converter
      shell: powershell
      run: |
        Invoke-WebRequest https://github.com/uup-dump/uup-dump/archive/refs/heads/master.zip -OutFile uup.zip
        Expand-Archive uup.zip -DestinationPath . -Force
        Rename-Item uup-dump-master uup

    - name: Instalar aria2
      shell: powershell
      run: |
        choco install aria2 -y
        $aria = (Get-Command aria2c).Source
        Copy-Item $aria "uup\files\aria2c.exe" -Force

    - name: Configurar build manual (Win11 Pro)
      shell: powershell
      run: |
        cd uup
        echo 22631.2861 > build.txt
        echo pt-br > lang.txt
        echo professional > edition.txt

    - name: Executar script
      shell: cmd
      working-directory: uup
      run: |
        uup_download_windows.cmd

    - name: Verificar ISO
      shell: powershell
      run: |
        Get-ChildItem -Recurse -Filter *.iso
