name: Build LTSC 2019 PTBR ISO (DVP FINAL FIXED)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Preparar pastas
      run: |
        mkdir C:\build
        mkdir C:\build\out

    - name: Baixar ISO base
      run: |
        powershell -Command "Invoke-WebRequest 'https://zerofs.link/f/gw2CD6ponn7Sy29DjwgZCL/' -OutFile 'C:\build\base.iso'"

    - name: Baixar DVP pt-BR
      run: |
        powershell -Command "Invoke-WebRequest 'https://zerofs.link/f/SkRCGLHjMCtWthKoNdz5Ds/' -OutFile 'C:\build\ptbr.dvp'"

    - name: Baixar DumbVersion Patcher
      run: |
        powershell -Command "Invoke-WebRequest 'https://github.com/thecatontheceiling/DumbVersion/releases/download/v1.2.2/DumbVersionPatcher-win-x64.exe' -OutFile 'C:\build\patcher.exe'"

    - name: Executar patcher
      run: |
        cd C:\build
        patcher.exe -bulk . . -o .

    - name: Localizar ISO gerada
      shell: cmd
      run: |
        for /r C:\build %%i in (*.iso) do set ISO=%%i
        echo ISO=%ISO%>> %GITHUB_ENV%

    - name: Compactar ISO em partes 1900MB
      run: |
        7z a -v1900m C:\build\out\windows_ltsc2019_ptbr.7z %ISO%

    - name: Criar Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ltsc2019-ptbr
        name: Windows LTSC 2019 PT-BR
        files: C:\build\out\*
